### ISSUE TITLE
Available Checkpoint

### ISSUE THREAD

**Issue by TaWald** [FengheTan9/HySparK#1]
Hello,
I was wondering if you could provide the associated checkpoint of your method as promised in the paper.
While the description on how to use it seems nice a checkpoint to drop in there would help a lot 😅 
Best,
Tassilo

**Comment by FengheTan9** [comment]
Thanks for your attention to our HySparK. We have uploaded the checkpoint, hope you enjoy [it](https://github.com/FengheTan9/HySparK/tree/main/ckpt) 🤗 ! 
If you have any questions feel free to contact me ~ 🤓

**Comment by TaWald** [comment]
Thank you very much
